routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('login/login');
});

/* Route Home*/
Route::resource('/dashboard', 'DashboardController');

/* Route Notice*/
Route::resource('/notice', 'NoticeController');
Route::any('/table/notice', 'NoticeController@dataTable')->name('table.notice');

/* Route Program Study*/
Route::resource('/program_study', 'ProgramStudyController');
Route::any('/table/program_study', 'ProgramStudyController@dataTable')->name('table.program_study');

/* Route Authen*/
Route::get('/login', 'AuthController@index')->name('login');
Route::post('/login','AuthController@proses_auth')->name('login.auth');
Route::get('/logout','AuthController@logout')->name('logout');

/* Route Program Study*/
Route::resource('/grade_student', 'GradeStudentController');
Route::any('/table/grade_student', 'GradeStudentController@dataTable')->name('table.grade_student');


/* Route Group*/
Route::resource('/group','GroupController');
Route::get('/table/group', 'GroupController@dataTable')->name('table.group');

/* Route Department*/
Route::resource('/department','DepartmentController');
Route::any('/table/department', 'DepartmentController@dataTable')->name('table.department');

/* Route Institution*/
Route::resource('/institution','InstitutionController');
Route::any('/table/institution', 'InstitutionController@dataTable')->name('table.institution');

/* Route Student*/
Route::resource('/student','StudentController');
Route::any('/table/student', 'StudentController@dataTable')->name('table.student');

/* Route Lecturer*/
Route::resource('/lecturer','LecturerController');
Route::any('/table/lecturer', 'LecturerController@dataTable')->name('table.lecturer');

/* Route GroupStudent*/
Route::resource('/groupstudent','GroupStudentController');
Route::any('/table/groupstudent', 'GroupStudentController@dataTable')->name('table.groupstudent');

/* Route GroupLecturer*/
Route::resource('/grouplecturer','GroupLecturerController');
Route::any('/table/grouplecturer', 'GroupLecturerController@dataTable')->name('table.grouplecturer');

/* Route DetailGroup*/
Route::get('/group/{id}/detail','DetailGroupController@index')->name('group.detail');
Route::post('/detailgroup/{id}', 'DetailGroupController@updatestudent')->name('detailgroup.updatestudent');
Route::post('/detailgroup2/{id}', 'DetailGroupController@updatelecturer')->name('detailgroup.updatelecturer');
Route::any('/table/dglecturer/{id}/detail', 'DetailGroupController@dataTableLecturer')->name('table.dglecturer');
Route::any('/table/dgstudent/{id}/detail', 'DetailGroupController@dataTableStudent')->name('table.dgstudent');

/* Route Manage Account*/
Route::resource('/manage_account','ManageAccountController');

/* Route Manage Group*/
Route::resource('/manage_group','ManageGroupController');


/* Route Profil*/
Route::resource('/profile', 'ProfileController');
Route::put('/updateProfil/{id}', 'ProfileController@update')->name('updateProfil');
Route::post('/updatePw/{id}', 'ProfileController@update_pw')->name('updatePw');

/* Route SubmissionProposal*/
Route::resource('/submission_proposal','SubmissionProposalController');
Route::post('/submission_proposal/{id}','SubmissionProposalController@update');
Route::any('/table/submission_proposal', 'SubmissionProposalController@dataTable')->name('table.submission_proposal');

/* Route Manage Proposal*/
Route::resource('/manage_proposal','ManageProposalController');
Route::any('/table/manage_proposal', 'ManageProposalController@dataTable')->name('table.manage_proposal');
Route::any('/table/riwayatpp', 'ManageProposalController@dataTable2')->name('table.riwayatpp');

/* Route Guidance*/
Route::resource('/guidance','GuidanceController');
Route::post('/guidance/{id}','GuidanceController@update');
Route::any('/table/guidance', 'GuidanceController@dataTable')->name('table.guidance');
Route::any('table/guidance2', 'GuidanceController@dataTable2')->name('table.guidance2');

/* Route Manage Proposal*/
Route::resource('/manage_guidance','ManageGuidanceController');
Route::post('/manage_guidance/{id}','ManageGuidanceController@update');
Route::get('/terima/{id}','ManageGuidanceController@edit2')->name('terima.edit2');
Route::any('/table/manage_guidance', 'ManageGuidanceController@dataTable')->name('table.manage_guidance');
Route::any('/table/riwayatbb', 'ManageGuidanceController@dataTable2')->name('table.riwayatbb');

/* Route DetailGuidance*/
Route::resource('/guidance_detail','DetailGuidanceController');

/* Route prasidang*/
Route::resource('/prasidang','PrasidangController');
Route::post('/prasidang/{id}','PrasidangController@update');
Route::any('/table/prasidang', 'PrasidangController@dataTable')->name('table.prasidang');


Route::resource('/manage_prasidang','ManagePrasidangController');
Route::any('/table/manage_prasidang', 'ManagePrasidangController@dataTable')->name('table.manage_prasidang');
Route::get('/grade/export_excel', 'GradeStudentController@export_excel')->name('grade');
Route::get('/grade/export_excel2', 'GradeStudentController@export_excel2')->name('grade2');
Route::get('/grade/export_excel3', 'GradeStudentController@export_excel3')->name('grade3');

Route::resource('/manage_grade','ManageGradeController');
Route::any('/table/manage_grade', 'ManageGradeController@dataTable')->name('table.manage_grade');

/* Route pascasidang*/
Route::resource('/pascasidang','PascasidangController');
Route::post('/pascasidang/{id}','PascasidangController@update');
Route::any('/table/pascasidang', 'PascasidangController@dataTable')->name('table.pascasidang');

Route::resource('/viewpasca','ViewpascaController');
Route::any('/table/pascati', 'ViewpascaController@dataTable')->name('table.pascati');
Route::any('/table/pascasi', 'ViewpascaController@dataTable2')->name('table.pascasi');
Route::any('/table/pascami', 'ViewpascaController@dataTable3')->name('table.pascami');

/* Route Manage Schedule*/
Route::resource('/manage_schedule', 'ManageScheduleController');

/* Route ScheduleStudent*/
Route::resource('/schedulestudent', 'ScheduleStudentController');
Route::any('/table/schedulestudent', 'ScheduleStudentController@dataTable')->name('table.schedulestudent');

/* Route ScheduleLecturer*/
Route::resource('/schedulelecturer', 'ScheduleLecturerController');
Route::any('/table/schedulelecturer', 'ScheduleLecturerController@dataTable')->name('table.schedulelecturer');

/* Route DetailSchedule*/
Route::get('/schedule/{id}/detail', 'DetailScheduleController@index')->name('schedule.detail');
Route::post('/detailschedule/{id}', 'DetailScheduleController@updatestudent')->name('detailschedule.updatestudent');
Route::post('/detailschedule2/{id}', 'DetailScheduleController@updatelecturer')->name('detailschedule.updatelecturer');
Route::any('/table/dslecturer/{id}/detail', 'DetailScheduleController@dataTableLecturer')->name('table.dslecturer');
Route::any('/table/dsstudent/{id}/detail', 'DetailScheduleController@dataTableStudent')->name('table.dsstudent');

/* Route schedule*/
Route::resource('/schedule', 'ScheduleController');
Route::get('/table/schedule', 'ScheduleController@dataTable')->name('table.mschedule');

/* Route view_schedule*/
Route::resource('/view_schedule', 'ViewScheduleController');
Route::any('/table/ViewSchedule', 'ViewScheduleController@dataTable')->name('table.schedule');

Route::get('/apidashboard', 'DashboardController@jumlahRow')->name('api.dashboard');
Route::get('/apijur', 'DashboardController@chartGrad')->name('front.grad');

Route::resource('/viewprasidang','ViewprasidangController');
Route::any('/table/prasidangti', 'ViewprasidangController@dataTable')->name('table.prasti');
Route::any('/table/prasidangsi', 'ViewprasidangController@dataTable2')->name('table.prassi');
Route::any('/table/prasidangmi', 'ViewprasidangController@dataTable3')->name('table.prascami');

app/Lecturer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Lecturer extends Model
{
    protected $primaryKey = 'nidn';
    public $incrementing = false;
}

app/Http/Controllers/LecturerController.php
<?php

namespace App\Http\Controllers;

use App\Lecturer;
use App\Auth;
use DataTables;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Session;

class LecturerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Session::get('login')){
            return view('lecturer/index');
        }else{
            return redirect('login');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Session::get('login')){
        $data = new Lecturer();
        return view('lecturer.form', compact('data'));
        }else{
            return redirect('login');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $id_auth = 'A'.date('dmy').Str::random(3);
        $this->validate(
            $request,
            [
                'nidn' => 'required',
                'nama' => 'required',
                'alamat' => 'required',
                'no_hp' => 'required',
                'email' => 'required',
                'pembimbing' => 'required',
                'penguji' => 'required',


            ],
            [
                'nidn.required' => 'Kolom nidn grup wajib diisi',
                'nama.required' => 'Kolom nama wajib diisi',
                'alamat.required' => 'Kolom alamat grup wajib diisi',
                'no_hp.required' => 'Kolom no hp wajib diisi',
                'email.required' => 'Kolom email grup wajib diisi',
                'pembimbing.required' => 'Kolom pembimbing wajib diisi',
                'penguji.required' => 'Kolom penguji wajib diisi'

            ]
        );
        $data = Lecturer::insert([
            [
                'nidn' => $request->nidn,
                'id_auth' => $id_auth,
                'nama' => $request->nama,
                'alamat' => $request->alamat,
                'email' => $request->email,
                'no_hp' => $request->no_hp,
                'pembimbing' => $request->pembimbing,
                'penguji' => $request->penguji,
                'created_at' => now()
            ]
        ]);
        
        $data = DB::table('auths')->insert([
            [
                'id_auth' => $id_auth,
                'username' => $request->nidn,
                'password' => bcrypt($request->nidn.'Dsn*'),
                'hak_akses' => 'dosen',
                'created_at' => now()
            ]
        ]);

        return $data;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(Session::get('login')){
        $data = Lecturer::findOrFail($id);
        return view('lecturer.form', compact('data'));
        }else{
            return redirect('login');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate(
            $request,
            [
                'nidn' => 'required',
                'nama' => 'required',
                'alamat' => 'required',
                'no_hp' => 'required',
                'email' => 'required',
                'pembimbing' => 'required',
                'penguji' => 'required',
            ],
            [
                'nidn.required' => 'Kolom nidn grup wajib diisi',
                'nama.required' => 'Kolom nama wajib diisi',
                'alamat.required' => 'Kolom alamat grup wajib diisi',
                'no_hp.required' => 'Kolom no hp wajib diisi',
                'email.required' => 'Kolom email grup wajib diisi',
                'pembimbing.required' => 'Kolom pembimbing wajib diisi',
                'penguji.required' => 'Kolom penguji wajib diisi'
            ]
        );

        $data = Lecturer::findOrFail($id);
        $data->nidn = $request->nidn;
        $data->nama = $request->nama;
          if (isset($request->check)) {
            $auth = Auth::findOrFail($data->id_auth);
            $auth->password = bcrypt($request->password);
            $auth->updated_at = now();
            $auth->save();
        }
        $data->alamat = $request->alamat;
        $data->no_hp = $request->no_hp;
        $data->email = $request->email;
        $data->updated_at = now();
        $data->save();

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Lecturer::findOrFail($id);
        $data->delete();
    }
    public function dataTable()
    {
        if(Session::get('login')){
        $data = Lecturer::query();
        return DataTables::of($data)
        ->addColumn('action', function($data){
            return view('layout._action_lecturer', [
                'data' => $data,
                'url_edit' => route('lecturer.edit', $data->nidn),
                'url_destroy' => route('lecturer.destroy', $data->nidn)
            ]);
        })
        ->addIndexColumn()
        ->rawColumns(['action'])
        ->make(true);
    }else{
        return redirect('login');
    }
    }
}

resources/views/lecturer/form.blade.php
{!! Form::model($data, [
'route' => $data->exists ? ['lecturer.update', $data->nidn] : ['lecturer.store'],
'method' => $data->exists ? 'PUT' : 'POST'
]) !!}
<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label for="" class="control-label">Nidn</label>
            {!! Form::text('nidn', null, ['class' => 'form-control', 'id' => 'nidn']) !!}
        </div>
        <div class="form-group">
            <label for="" class="control-label">Nama</label>
            {!! Form::text('nama', null, ['class' => 'form-control', 'id' => 'nama']) !!}
        </div>
        <div class="form-group">
            <label for="" class="control-label">No Hp</label>
            {!! Form::text('no_hp', null, ['class' => 'form-control', 'id' => 'no_hp']) !!}
        </div>
        <div class="form-group">
            <label for="" class="control-label">Email</label>
            {!! Form::email('email', null, ['class' => 'form-control', 'id' => 'email']) !!}
        </div>
        @if ($data->exists)
        <label for="" class="control-label">Reset Password</label>
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">
                    <input type="checkbox" value="check" name="check">
                </span>
            </div>
            <input type="text" class="form-control" name="password" value="{{$data->nidn.'Dsn*'}}" readonly>
        </div>
        @endif
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <label for="" class="control-label">Pembimbing</label>
            {!! Form::select('pembimbing', ['Ya' => 'Ya', 'Tidak' => 'Tidak'], null, ['class' => 'form-control',
            'placeholder' => 'Pilih ..']) !!}
        </div>
        <div class="form-group">
            <label for="" class="control-label">Penguji</label>
            {!! Form::select('penguji', ['Ya' => 'Ya', 'Tidak' => 'Tidak'], null, ['class' => 'form-control',
            'placeholder' => 'Pilih ..']) !!}
        </div>
        <div class="form-group">
            <label for="" class="control-label">Alamat</label>
            {!! Form::textarea('alamat', null, ['class' => 'form-control', 'id' => 'alamat','rows'=>'5']) !!}
        </div>

    </div>
</div>
{!! Form::close() !!}

resources/views/lecturer/index.blade.php
@extends('layout/main')
@section('title', 'Dosen')
@push('css')
<link rel="stylesheet" href="{{ asset('plugins/datatables-bs4/css/dataTables.bootstrap4.css')}}">
<link rel="stylesheet" href="{{ asset('plugins/sweetalert2/sweetalert2.min.css') }}">
@endpush
@section('breadcrumb')
<section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>Data Dosen</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Data Dosen</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>
@endsection
@section('content')
<section class="content">
    <div class="row">
      <div class="col-12">
        <!-- /.card -->
        <div class="card">
          <div class="card-header">
            <a href="{{ route('lecturer.create')}}" class="btn btn-primary modal-show" title="Tambah Data">Tambah</a>
          </div>
          <!-- /.card-header -->
          <div class="card-body table-responsive">
            <table id="example1" class="table table-bordered table-striped">
              <thead>
              <tr>
                <th>No</th>
                <th>Nama</th>
                <th>Email</th>
                <th>Alamat</th>
                <th>Aksi</th>
              </tr>
              </thead>
              <tbody>
              </tbody>
              <tfoot>
              <tr>
                <th>No</th>
                <th>Nama</th>
                <th>Email</th>
                <th>Alamat</th>
                <th>Aksi</th>
              </tr>
              </tfoot>
            </table>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
    @include('layout/_modal')
  </section>
@endsection
@push('js')
<script src="{{ asset('plugins/datatables/jquery.dataTables.js')}}"></script>
<script src="{{ asset('plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>
<script src="{{ asset('plugins/sweetalert2/sweetalert2.min.js') }}"></script>
<script src="{{ asset('js/app.js') }}"></script>
<script>
  $(function () {
    $('#example1').DataTable({
      responsive : true,
      processing : true,
      serverSide : true,
      order: [[1, 'asc']],
        ajax: {
            'url':"{{route('table.lecturer')}}",
            'type': 'POST',
            'headers': {
            'X-CSRF-TOKEN': '{{ csrf_token() }}'
            }
            },
      columns: [
        {data: 'DT_RowIndex', name:'nidn'},
        {data: 'nama', name:'nama'},
        {data: 'email', name:'email'},
        {data: 'alamat', name:'alamat'},
        {data: 'action', name: 'action'}
      ],
      columnDefs: [
        {
          "targets": [0, -1],
          "orderable": false,
          "searchable" : false
        }
      ]
      
    });
  });
</script>
@endpush