routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('login/login');
});

/* Route Home*/
Route::resource('/dashboard', 'DashboardController');

/* Route Notice*/
Route::resource('/notice', 'NoticeController');
Route::any('/table/notice', 'NoticeController@dataTable')->name('table.notice');

/* Route Program Study*/
Route::resource('/program_study', 'ProgramStudyController');
Route::any('/table/program_study', 'ProgramStudyController@dataTable')->name('table.program_study');

/* Route Authen*/
Route::get('/login', 'AuthController@index')->name('login');
Route::post('/login','AuthController@proses_auth')->name('login.auth');
Route::get('/logout','AuthController@logout')->name('logout');

/* Route Program Study*/
Route::resource('/grade_student', 'GradeStudentController');
Route::any('/table/grade_student', 'GradeStudentController@dataTable')->name('table.grade_student');


/* Route Group*/
Route::resource('/group','GroupController');
Route::get('/table/group', 'GroupController@dataTable')->name('table.group');

/* Route Department*/
Route::resource('/department','DepartmentController');
Route::any('/table/department', 'DepartmentController@dataTable')->name('table.department');

/* Route Institution*/
Route::resource('/institution','InstitutionController');
Route::any('/table/institution', 'InstitutionController@dataTable')->name('table.institution');

/* Route Student*/
Route::resource('/student','StudentController');
Route::any('/table/student', 'StudentController@dataTable')->name('table.student');

/* Route Lecturer*/
Route::resource('/lecturer','LecturerController');
Route::any('/table/lecturer', 'LecturerController@dataTable')->name('table.lecturer');

/* Route GroupStudent*/
Route::resource('/groupstudent','GroupStudentController');
Route::any('/table/groupstudent', 'GroupStudentController@dataTable')->name('table.groupstudent');

/* Route GroupLecturer*/
Route::resource('/grouplecturer','GroupLecturerController');
Route::any('/table/grouplecturer', 'GroupLecturerController@dataTable')->name('table.grouplecturer');

/* Route DetailGroup*/
Route::get('/group/{id}/detail','DetailGroupController@index')->name('group.detail');
Route::post('/detailgroup/{id}', 'DetailGroupController@updatestudent')->name('detailgroup.updatestudent');
Route::post('/detailgroup2/{id}', 'DetailGroupController@updatelecturer')->name('detailgroup.updatelecturer');
Route::any('/table/dglecturer/{id}/detail', 'DetailGroupController@dataTableLecturer')->name('table.dglecturer');
Route::any('/table/dgstudent/{id}/detail', 'DetailGroupController@dataTableStudent')->name('table.dgstudent');

/* Route Manage Account*/
Route::resource('/manage_account','ManageAccountController');

/* Route Manage Group*/
Route::resource('/manage_group','ManageGroupController');


/* Route Profil*/
Route::resource('/profile', 'ProfileController');
Route::put('/updateProfil/{id}', 'ProfileController@update')->name('updateProfil');
Route::post('/updatePw/{id}', 'ProfileController@update_pw')->name('updatePw');

/* Route SubmissionProposal*/
Route::resource('/submission_proposal','SubmissionProposalController');
Route::post('/submission_proposal/{id}','SubmissionProposalController@update');
Route::any('/table/submission_proposal', 'SubmissionProposalController@dataTable')->name('table.submission_proposal');

/* Route Manage Proposal*/
Route::resource('/manage_proposal','ManageProposalController');
Route::any('/table/manage_proposal', 'ManageProposalController@dataTable')->name('table.manage_proposal');
Route::any('/table/riwayatpp', 'ManageProposalController@dataTable2')->name('table.riwayatpp');

/* Route Guidance*/
Route::resource('/guidance','GuidanceController');
Route::post('/guidance/{id}','GuidanceController@update');
Route::any('/table/guidance', 'GuidanceController@dataTable')->name('table.guidance');
Route::any('table/guidance2', 'GuidanceController@dataTable2')->name('table.guidance2');

/* Route Manage Proposal*/
Route::resource('/manage_guidance','ManageGuidanceController');
Route::post('/manage_guidance/{id}','ManageGuidanceController@update');
Route::get('/terima/{id}','ManageGuidanceController@edit2')->name('terima.edit2');
Route::any('/table/manage_guidance', 'ManageGuidanceController@dataTable')->name('table.manage_guidance');
Route::any('/table/riwayatbb', 'ManageGuidanceController@dataTable2')->name('table.riwayatbb');

/* Route DetailGuidance*/
Route::resource('/guidance_detail','DetailGuidanceController');

/* Route prasidang*/
Route::resource('/prasidang','PrasidangController');
Route::post('/prasidang/{id}','PrasidangController@update');
Route::any('/table/prasidang', 'PrasidangController@dataTable')->name('table.prasidang');


Route::resource('/manage_prasidang','ManagePrasidangController');
Route::any('/table/manage_prasidang', 'ManagePrasidangController@dataTable')->name('table.manage_prasidang');
Route::get('/grade/export_excel', 'GradeStudentController@export_excel')->name('grade');
Route::get('/grade/export_excel2', 'GradeStudentController@export_excel2')->name('grade2');
Route::get('/grade/export_excel3', 'GradeStudentController@export_excel3')->name('grade3');

Route::resource('/manage_grade','ManageGradeController');
Route::any('/table/manage_grade', 'ManageGradeController@dataTable')->name('table.manage_grade');

/* Route pascasidang*/
Route::resource('/pascasidang','PascasidangController');
Route::post('/pascasidang/{id}','PascasidangController@update');
Route::any('/table/pascasidang', 'PascasidangController@dataTable')->name('table.pascasidang');

Route::resource('/viewpasca','ViewpascaController');
Route::any('/table/pascati', 'ViewpascaController@dataTable')->name('table.pascati');
Route::any('/table/pascasi', 'ViewpascaController@dataTable2')->name('table.pascasi');
Route::any('/table/pascami', 'ViewpascaController@dataTable3')->name('table.pascami');

/* Route Manage Schedule*/
Route::resource('/manage_schedule', 'ManageScheduleController');

/* Route ScheduleStudent*/
Route::resource('/schedulestudent', 'ScheduleStudentController');
Route::any('/table/schedulestudent', 'ScheduleStudentController@dataTable')->name('table.schedulestudent');

/* Route ScheduleLecturer*/
Route::resource('/schedulelecturer', 'ScheduleLecturerController');
Route::any('/table/schedulelecturer', 'ScheduleLecturerController@dataTable')->name('table.schedulelecturer');

/* Route DetailSchedule*/
Route::get('/schedule/{id}/detail', 'DetailScheduleController@index')->name('schedule.detail');
Route::post('/detailschedule/{id}', 'DetailScheduleController@updatestudent')->name('detailschedule.updatestudent');
Route::post('/detailschedule2/{id}', 'DetailScheduleController@updatelecturer')->name('detailschedule.updatelecturer');
Route::any('/table/dslecturer/{id}/detail', 'DetailScheduleController@dataTableLecturer')->name('table.dslecturer');
Route::any('/table/dsstudent/{id}/detail', 'DetailScheduleController@dataTableStudent')->name('table.dsstudent');

/* Route schedule*/
Route::resource('/schedule', 'ScheduleController');
Route::get('/table/schedule', 'ScheduleController@dataTable')->name('table.mschedule');

/* Route view_schedule*/
Route::resource('/view_schedule', 'ViewScheduleController');
Route::any('/table/ViewSchedule', 'ViewScheduleController@dataTable')->name('table.schedule');

Route::get('/apidashboard', 'DashboardController@jumlahRow')->name('api.dashboard');
Route::get('/apijur', 'DashboardController@chartGrad')->name('front.grad');

Route::resource('/viewprasidang','ViewprasidangController');
Route::any('/table/prasidangti', 'ViewprasidangController@dataTable')->name('table.prasti');
Route::any('/table/prasidangsi', 'ViewprasidangController@dataTable2')->name('table.prassi');
Route::any('/table/prasidangmi', 'ViewprasidangController@dataTable3')->name('table.prascami');

app/SubmissionProposal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SubmissionProposal extends Model
{
    protected $primaryKey = 'id_pp';
    public $incrementing = false;
    protected $table = 'submissions_proposal';
}

resources/views/submission_proposal/edit.blade.php
<form action="{{ route('submission_proposal.update', $data->id_pp) }}" enctype="multipart/form-data" method="POST">
    @csrf
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="" class="control-label">Topik Skripsi</label>
                <input type="text" name="topik_skripsi" class="form-control" id="topik_skripsi"
                    value="{{$data->topik_skripsi}}">
            </div>
            <div class="form-group">
                <label for="" class="control-label">File KRS</label>
                <input type="file" class="form-control" id="file_krs" name="file_krs">
                <input type="hidden" name="old_file_krs" value="{{ $data->file_krs }}">
            </div>
            <div class="form-group">
                <label for="" class="control-label">File KHS</label>
                <input type="file" name="file_khs" class="form-control" id="file_khs">
                <input type="hidden" name="old_file_khs" value="{{ $data->file_khs }}">
            </div>
            <div class="form-group">
                <label for="" class="control-label">File Proposal</label>
                <input type="file" name="file_proposal" class="form-control" id="file_proposal">
                <input type="hidden" name="old_file_proposal" value="{{ $data->file_proposal }}">
            </div>
            <div class="form-group">
                <label for="" class="control-label">Tanggal</label>
                <input type="date" name="tanggal" class="form-control" id="tanggal"
                    value="{{ isset($data) ? $data->tanggal : '' }}">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12" align="right">
            <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
            <button type="submit" class="btn btn-primary">Edit</button>
        </div>
    </div>
</form>

resources/views/submission_proposal/form.blade.php
<form action="{{ route('submission_proposal.store') }}" enctype="multipart/form-data" method="POST">
    @csrf
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="" class="control-label">Topik Skripsi</label>
                <input type="text" name="topik_skripsi" class="form-control" id="topik_skripsi"
                    value=" {{ isset($data) ? $data->topik_skripsi : '' }}">
            </div>
            <div class="form-group">
                <label for="" class="control-label">File KRS</label>
                <input type="file" class="form-control" id="file_krs" name="file_krs" required>
            </div>
            <div class="form-group">
                <label for="" class="control-label">File KHS</label>
                <input type="file" name="file_khs" class="form-control" id="file_khs" required>
            </div>
            <div class="form-group">
                <label for="" class="control-label">File Proposal</label>
                <input type="file" name="file_proposal" class="form-control" id="file_proposal" required>
            </div>
            <div class="form-group">
                <label for="" class="control-label">Tanggal</label>
                <input type="date" name="tanggal" class="form-control" id="tanggal" required>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12" align="right">
            <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
            <button type="submit" class="btn btn-primary">Simpan</button>
        </div>
    </div>
</form>

resources/views/submission_proposal/index.blade.php
@extends('layout/main')
@section('title', 'Pengajuan Proposal')
@push('css')
<link rel="stylesheet" href="{{ asset('plugins/datatables-bs4/css/dataTables.bootstrap4.css')}}">
<link rel="stylesheet" href="{{ asset('plugins/sweetalert2/sweetalert2.min.css') }}">
@endpush
@section('breadcrumb')
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Data Pengajuan Proposal</h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item active">Data Pengajuan Proposal</li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</section>
@endsection
@section('content')
<section class="content">
  @if (Session::has('success'))
  <div class="row">
    <div class="col-12">
      <div class="alert alert-success">
        {{ Session::get('success') }}
      </div>
    </div>
  </div>
  @elseif(Session::has('error'))
  <div class="row">
    <div class="col-12">
      <div class="alert alert-danger">
        {{ Session::get('error') }}
      </div>
    </div>
  </div>
  @endif
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3">
        <!-- Profile Image -->
        <div class="card card-primary card-outline">
          <div class="card-body box-profile">
            <div class="text-center">
              <img class="profile-user-img img-fluid img-circle" src="{{asset('dist/img/avatar.png')}}"
                alt="User profile picture">
            </div>
            <h3 class="profile-username text-center">{{$data->nama}}</h3>
            <p class="text-muted text-center">
            </p>
            <ul class="list-group list-group-unbordered mb-3">
              <li class="list-group-item">
                <p class="text text-center">HP : {{$data->no_hp}} </p>
                <p class="text text-center">Nilai Proposal : {{ $data2 != NULL ? $data2->nilai_pengajuan : '-' }}</p>
              </li>
            </ul>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
      <!-- /.col -->
      <div class="col-9">
        <!-- /.card -->
        <div class="card">
          <div class="card-header">
            <a href="{{ route('submission_proposal.create')}}" class="btn btn-primary modalnofooter-show"
              title="Tambah Data">Tambah</a>
          </div>
          <!-- /.card-header -->
          <div class="card-body table-responsive">
            <table id="example1" class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>No</th>
                  <th>Topik Skripsi</th>
                  <th>File Krs</th>
                  <th>File Khs</th>
                  <th>File Proposal</th>
                  <th>Tanggal Pengajuan</th>
                  <th>Status</th>
                  <th>Aksi</th>
                </tr>
              </thead>
              <tbody>
              </tbody>
              <tfoot>
                <tr>
                  <th>No</th>
                  <th>Topik Skripsi</th>
                  <th>File Krs</th>
                  <th>File Khs</th>
                  <th>File Proposal</th>
                  <th>Tanggal Pengajuan</th>
                  <th>Status</th>
                  <th>Aksi</th>
                </tr>
              </tfoot>
            </table>
          </div>
          <div class="card-footer">
            <p>Cek Proposal Pengajuan Anda Sebelum diajukan agar terhindar dari plagiatrisme<a
                href="https://smallseotools.com/plagiarism-checker/" target="_blank"> Website Cek Plagiat !</a></p>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
      @include('layout/_modal_without_footer')
</section>
@endsection
@push('js')
<script src="{{ asset('plugins/datatables/jquery.dataTables.js')}}"></script>
<script src="{{ asset('plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>
<script src="{{ asset('plugins/sweetalert2/sweetalert2.min.js') }}"></script>
<script src="{{ asset('js/app.js') }}"></script>
<script>
  $(document).ready(function() {
    $('body').on('click', '.modalnofooter-show', function(e) {
      e.preventDefault();
      var me = $(this),
        url = me.attr('href'),
        form = $('.modal-body form'),
        title = me.attr('title');
      $.ajax({
        url: url,
        dataType: 'html',
        success: function(response) {
          $('#modal-body-nofooter').html(response);
        }
      });

      $('#modal-nofooter').modal('show');
    });
  });
</script>
<script>
  $(function() {
    $('#example1').DataTable({
      responsive: true,
      processing: true,
      serverSide: true,
      order: [
        [1, 'asc']
      ],
      ajax: {
        'url': "{{route('table.submission_proposal')}}",
        'type': 'POST',
        'headers': {
          'X-CSRF-TOKEN': '{{ csrf_token() }}'
        }
      },
      columns: [{
          data: 'DT_RowIndex',
          name: 'id_pp'
        },
        {
          data: 'topik_skripsi',
          name: 'topik_skripsi'
        },
        {
          data: 'krs',
          name: 'krs'
        },
        {
          data: 'khs',
          name: 'khs'
        },
        {
          data: 'proposal',
          name: 'proposal'
        },
        {
          data: 'tanggal',
          name: 'tanggal'
        },
        {
          data: 'status',
          name: 'status'
        },
        {
          data: 'action',
          name: 'action'
        }
      ],
      columnDefs: [{
        "targets": [0, -1],
        "orderable": false,
        "searchable": false
      }]

    });
  });
</script>
@endpush

resources/views/submission_proposal/link_download.blade.php
<a href="{{ $url_download }}" target="_blank">{{ $title }}</a>

resources/views/submission_proposal/status.blade.php
@if ($data->status == 'terima')
<span class="text text-success">
    <i class="fa fa-check-circle"></i> Diterima
</span>
@elseif($data->status == 'tolak')
<span class="text text-danger">
    <i class="fa fa-times-circle"></i> Ditolak
</span>
@elseif($data->status == 'proses')
<span class="text text-primary">
    <i class="fa fa-times-circle"></i> Sedang Diproses
</span>
@endif