routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('login/login');
});

/* Route Home*/
Route::resource('/dashboard', 'DashboardController');

/* Route Notice*/
Route::resource('/notice', 'NoticeController');
Route::any('/table/notice', 'NoticeController@dataTable')->name('table.notice');

/* Route Program Study*/
Route::resource('/program_study', 'ProgramStudyController');
Route::any('/table/program_study', 'ProgramStudyController@dataTable')->name('table.program_study');

/* Route Authen*/
Route::get('/login', 'AuthController@index')->name('login');
Route::post('/login','AuthController@proses_auth')->name('login.auth');
Route::get('/logout','AuthController@logout')->name('logout');

/* Route Program Study*/
Route::resource('/grade_student', 'GradeStudentController');
Route::any('/table/grade_student', 'GradeStudentController@dataTable')->name('table.grade_student');


/* Route Group*/
Route::resource('/group','GroupController');
Route::get('/table/group', 'GroupController@dataTable')->name('table.group');

/* Route Department*/
Route::resource('/department','DepartmentController');
Route::any('/table/department', 'DepartmentController@dataTable')->name('table.department');

/* Route Institution*/
Route::resource('/institution','InstitutionController');
Route::any('/table/institution', 'InstitutionController@dataTable')->name('table.institution');

/* Route Student*/
Route::resource('/student','StudentController');
Route::any('/table/student', 'StudentController@dataTable')->name('table.student');

/* Route Lecturer*/
Route::resource('/lecturer','LecturerController');
Route::any('/table/lecturer', 'LecturerController@dataTable')->name('table.lecturer');

/* Route GroupStudent*/
Route::resource('/groupstudent','GroupStudentController');
Route::any('/table/groupstudent', 'GroupStudentController@dataTable')->name('table.groupstudent');

/* Route GroupLecturer*/
Route::resource('/grouplecturer','GroupLecturerController');
Route::any('/table/grouplecturer', 'GroupLecturerController@dataTable')->name('table.grouplecturer');

/* Route DetailGroup*/
Route::get('/group/{id}/detail','DetailGroupController@index')->name('group.detail');
Route::post('/detailgroup/{id}', 'DetailGroupController@updatestudent')->name('detailgroup.updatestudent');
Route::post('/detailgroup2/{id}', 'DetailGroupController@updatelecturer')->name('detailgroup.updatelecturer');
Route::any('/table/dglecturer/{id}/detail', 'DetailGroupController@dataTableLecturer')->name('table.dglecturer');
Route::any('/table/dgstudent/{id}/detail', 'DetailGroupController@dataTableStudent')->name('table.dgstudent');

/* Route Manage Account*/
Route::resource('/manage_account','ManageAccountController');

/* Route Manage Group*/
Route::resource('/manage_group','ManageGroupController');


/* Route Profil*/
Route::resource('/profile', 'ProfileController');
Route::put('/updateProfil/{id}', 'ProfileController@update')->name('updateProfil');
Route::post('/updatePw/{id}', 'ProfileController@update_pw')->name('updatePw');

/* Route SubmissionProposal*/
Route::resource('/submission_proposal','SubmissionProposalController');
Route::post('/submission_proposal/{id}','SubmissionProposalController@update');
Route::any('/table/submission_proposal', 'SubmissionProposalController@dataTable')->name('table.submission_proposal');

/* Route Manage Proposal*/
Route::resource('/manage_proposal','ManageProposalController');
Route::any('/table/manage_proposal', 'ManageProposalController@dataTable')->name('table.manage_proposal');
Route::any('/table/riwayatpp', 'ManageProposalController@dataTable2')->name('table.riwayatpp');

/* Route Guidance*/
Route::resource('/guidance','GuidanceController');
Route::post('/guidance/{id}','GuidanceController@update');
Route::any('/table/guidance', 'GuidanceController@dataTable')->name('table.guidance');
Route::any('table/guidance2', 'GuidanceController@dataTable2')->name('table.guidance2');

/* Route Manage Proposal*/
Route::resource('/manage_guidance','ManageGuidanceController');
Route::post('/manage_guidance/{id}','ManageGuidanceController@update');
Route::get('/terima/{id}','ManageGuidanceController@edit2')->name('terima.edit2');
Route::any('/table/manage_guidance', 'ManageGuidanceController@dataTable')->name('table.manage_guidance');
Route::any('/table/riwayatbb', 'ManageGuidanceController@dataTable2')->name('table.riwayatbb');

/* Route DetailGuidance*/
Route::resource('/guidance_detail','DetailGuidanceController');

/* Route prasidang*/
Route::resource('/prasidang','PrasidangController');
Route::post('/prasidang/{id}','PrasidangController@update');
Route::any('/table/prasidang', 'PrasidangController@dataTable')->name('table.prasidang');


Route::resource('/manage_prasidang','ManagePrasidangController');
Route::any('/table/manage_prasidang', 'ManagePrasidangController@dataTable')->name('table.manage_prasidang');
Route::get('/grade/export_excel', 'GradeStudentController@export_excel')->name('grade');
Route::get('/grade/export_excel2', 'GradeStudentController@export_excel2')->name('grade2');
Route::get('/grade/export_excel3', 'GradeStudentController@export_excel3')->name('grade3');

Route::resource('/manage_grade','ManageGradeController');
Route::any('/table/manage_grade', 'ManageGradeController@dataTable')->name('table.manage_grade');

/* Route pascasidang*/
Route::resource('/pascasidang','PascasidangController');
Route::post('/pascasidang/{id}','PascasidangController@update');
Route::any('/table/pascasidang', 'PascasidangController@dataTable')->name('table.pascasidang');

Route::resource('/viewpasca','ViewpascaController');
Route::any('/table/pascati', 'ViewpascaController@dataTable')->name('table.pascati');
Route::any('/table/pascasi', 'ViewpascaController@dataTable2')->name('table.pascasi');
Route::any('/table/pascami', 'ViewpascaController@dataTable3')->name('table.pascami');

/* Route Manage Schedule*/
Route::resource('/manage_schedule', 'ManageScheduleController');

/* Route ScheduleStudent*/
Route::resource('/schedulestudent', 'ScheduleStudentController');
Route::any('/table/schedulestudent', 'ScheduleStudentController@dataTable')->name('table.schedulestudent');

/* Route ScheduleLecturer*/
Route::resource('/schedulelecturer', 'ScheduleLecturerController');
Route::any('/table/schedulelecturer', 'ScheduleLecturerController@dataTable')->name('table.schedulelecturer');

/* Route DetailSchedule*/
Route::get('/schedule/{id}/detail', 'DetailScheduleController@index')->name('schedule.detail');
Route::post('/detailschedule/{id}', 'DetailScheduleController@updatestudent')->name('detailschedule.updatestudent');
Route::post('/detailschedule2/{id}', 'DetailScheduleController@updatelecturer')->name('detailschedule.updatelecturer');
Route::any('/table/dslecturer/{id}/detail', 'DetailScheduleController@dataTableLecturer')->name('table.dslecturer');
Route::any('/table/dsstudent/{id}/detail', 'DetailScheduleController@dataTableStudent')->name('table.dsstudent');

/* Route schedule*/
Route::resource('/schedule', 'ScheduleController');
Route::get('/table/schedule', 'ScheduleController@dataTable')->name('table.mschedule');

/* Route view_schedule*/
Route::resource('/view_schedule', 'ViewScheduleController');
Route::any('/table/ViewSchedule', 'ViewScheduleController@dataTable')->name('table.schedule');

Route::get('/apidashboard', 'DashboardController@jumlahRow')->name('api.dashboard');
Route::get('/apijur', 'DashboardController@chartGrad')->name('front.grad');

Route::resource('/viewprasidang','ViewprasidangController');
Route::any('/table/prasidangti', 'ViewprasidangController@dataTable')->name('table.prasti');
Route::any('/table/prasidangsi', 'ViewprasidangController@dataTable2')->name('table.prassi');
Route::any('/table/prasidangmi', 'ViewprasidangController@dataTable3')->name('table.prascami');

app/Pascasidang.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pascasidang extends Model
{
    protected $primaryKey = 'id_pcs';
    public $incrementing = false;
    protected $table = 'pascasidang';
}

app/Http/Controllers/PascasidangController.php
<?php

namespace App\Http\Controllers;

use App\Pascasidang;
use App\Student;
use DataTables;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Session;
use File;
use Storage;
use Illuminate\Http\Request;

class PascasidangController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Session::get('login')) {
            if (Session::get('hak_akses') == 'mahasiswa') {
                $data = DB::table('students')
                    ->join('auths', 'students.id_auth', '=', 'auths.id_auth')
                    ->select('students.*', 'auths.*')
                    ->where('auths.id_auth', Session::get('id_auth'))
                    ->first();
            } else if (Session::get('hak_akses') == 'dosen') {
                $data = DB::table('lecturers')
                    ->join('auths', 'lecturers.id_auth', '=', 'auths.id_auth')
                    ->select('lecturers.*', 'auths.*')
                    ->where('auths.id_auth', Session::get('id_auth'))
                    ->first();
            } else if (Session::get('hak_akses') == 'lppm') {
                $data = DB::table('institutions')
                    ->join('auths', 'institutions.id_auth', '=', 'auths.id_auth')
                    ->select('institutions.*', 'auths.*')
                    ->where('auths.id_auth', Session::get('id_auth'))
                    ->first();
            } else if (Session::get('hak_akses') == 'prodi') {
                $data = DB::table('departments')
                    ->join('auths', 'departments.id_auth', '=', 'auths.id_auth')
                    ->select('departments.*', 'auths.*')
                    ->where('auths.id_auth', Session::get('id_auth'))
                    ->first();
            }
            return view('pascasidang/index', compact('data'));
        } else {
            return redirect('login');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Session::get('login')){
        return view('pascasidang.form');
        }else{
            return redirect('login');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $id_ps = 'PS' . date('dmy') . Str::random(2);
        $this->validate(
            $request,
            [
                'file_skripsi' => 'required|mimes:docx,doc,pdf'

            ],
            [

                'file_skripsi.required' => 'Wajib mengunggah file skripsi',
                'file_skripsi.mimes' => 'Format file salah',


            ]
        );
        $file_skripsi = 'SKI' . Str::replaceFirst('.', '', Session::get('username')) . '-' . date('His');
        $extension_skripsi = $request->file_skripsi->getClientOriginalExtension();
        $request->file_skripsi->move(public_path('upload/pascasidang'), $file_skripsi . '.' . $extension_skripsi);

        $data = Pascasidang::insert([
            [
                'id_pcs' => $id_ps,
                'nim' => Session::get('username'),
                'file_skripsi' => $file_skripsi . '.' . $extension_skripsi,
                'tanggal' => $request->tanggal,
                'created_at' => now()

            ]
        ]);

        if ($data) {
            $request->session()->flash('success', 'Data berhasil ditambahkan');
        } else {
            $request->session()->flash('error', 'Data gagal ditambahkan');
        }

        return redirect('pascasidang');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(Session::get('login')){
        $data = Pascasidang::findOrFail($id);
        return view('pascasidang/edit', compact('data'));
        }else{
            return redirect('login');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate(
            $request,
            [
                'file_skripsi' => 'required|mimes:docx,doc,pdf'

            ],
            [

                'file_skripsi.required' => 'Wajib mengunggah file skripsi',
                'file_skripsi.mimes' => 'Format file salah',



            ]
        );
        $data = Pascasidang::findOrFail($id);
        $file_skripsi = $request->file_skripsi;
        if ($file_skripsi == NULL) {
            $file_skripsi = $request->old_file_skripsi;
        } else {
            unlink(public_path('upload/pascasidang/' . $data->file_skripsi));
            $fileName = 'SKI' . Str::replaceFirst('.', '', Session::get('username')) . '-' . date('His');
            $extension = $request->file_skripsi->getClientOriginalExtension();
            $request->file_skripsi->move(public_path('upload/pascasidang'), $fileName . '.' . $extension);
            $file_skripsi = $fileName . '.' . $extension;
        }

        $data->file_skripsi = $file_skripsi;
        $data->tanggal = $request->tanggal;
        $data->save();

        $request->session()->flash('success', 'Data berhasil diubah');
        return redirect('pascasidang');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function dataTable()
    {
        if(Session::get('login')){
        $data = DB::table('pascasidang')
            ->join('students', 'pascasidang.nim', '=', 'students.nim')
            ->select('students.*', 'pascasidang.*')
            ->where([['students.nim', '=', Session::get('username')], ['students.tahun', '=', date('Y')]])
            ->get();
        return DataTables::of($data)
            ->addColumn('skripsi', function ($data) {
                $path = 'upload/pascasidang/' . $data->file_skripsi;
                return view('pascasidang.link_download', [
                    'data' => $data,
                    'title' => $data->file_skripsi,
                    'url_download' => $path
                ]);
            })
            ->addColumn('action', function ($data) {
                return view('layout._action_pcs', [
                    'data' => $data,
                    'url_edit' => route('pascasidang.edit', $data->id_pcs)
                ]);
            })
            ->addIndexColumn()
            ->rawColumns(['skripsi', 'action'])
            ->make(true);
        }else{
            return redirect('login');
        }
    }
}

resources/views/pascasidang/edit.blade.php
<form action="{{ route('pascasidang.update', $data->id_pcs) }}" enctype="multipart/form-data" method="POST">
    @csrf
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="" class="control-label">File Skripsi</label>
                <input type="file" name="file_skripsi" class="form-control" id="file_skripsi">
                <input type="hidden" name="old_file_skripsi" value="{{ $data->file_skripsi }}">
            </div>
            <div class="form-group">
                <label for="" class="control-label">Tanggal</label>
                <input type="date" name="tanggal" class="form-control" id="tanggal"
                    value="{{ isset($data) ? $data->tanggal : '' }}">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12" align="right">
            <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
            <button type="submit" class="btn btn-primary">Edit</button>
        </div>
    </div>
</form>

resources/views/pascasidang/form.blade.php
<form action="{{ route('pascasidang.store') }}" enctype="multipart/form-data" method="POST">
    @csrf
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="" class="control-label">File Skripsi</label>
                <input type="file" name="file_skripsi" class="form-control" id="file_skripsi"
                    accept="application/pdf, application/msword" required>
            </div>
            <div class="form-group">
                <label for="" class="control-label">Tanggal</label>
                <input type="date" name="tanggal" class="form-control" id="tanggal" required>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12" align="right">
            <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
            <button type="submit" class="btn btn-primary">Simpan</button>
        </div>
    </div>
</form>

resources/views/pascasidang/index.blade.php
@extends('layout/main')
@section('title', 'Pasca Sidang')
@push('css')
<link rel="stylesheet" href="{{ asset('plugins/datatables-bs4/css/dataTables.bootstrap4.css')}}">
<link rel="stylesheet" href="{{ asset('plugins/sweetalert2/sweetalert2.min.css') }}">
@endpush
@section('breadcrumb')
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Data Pasca Sidang</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Data Pasca Sidang</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
@endsection
@section('content')
<section class="content">
    @if (Session::has('success'))
    <div class="row">
        <div class="col-12">
            <div class="alert alert-success">
                {{ Session::get('success') }}
            </div>
        </div>
    </div>
    @elseif(Session::has('error'))
    <div class="row">
        <div class="col-12">
            <div class="alert alert-danger">
                {{ Session::get('error') }}
            </div>
        </div>
    </div>
    @endif
    <div class="container-fluid">
        <div class="row">
            <!-- /.col -->
            <div class="col-md-12">
                <!-- /.card -->
                <div class="card">
                    <div class="card-header">
                        <a href="{{ route('pascasidang.create')}}" class="btn btn-primary modalnofooter-show" title="Tambah Data">Tambah</a>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body table-responsive">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>File Skripsi</th>
                                    <th>Tanggal</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>No</th>
                                    <th>File Skripsi</th>
                                    <th>Tanggal</th>
                                    <th>Aksi</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            @include('layout/_modal_without_footer')
</section>
@endsection
@push('js')
<script src="{{ asset('plugins/datatables/jquery.dataTables.js')}}"></script>
<script src="{{ asset('plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>
<script src="{{ asset('plugins/sweetalert2/sweetalert2.min.js') }}"></script>
<script src="{{ asset('js/app.js') }}"></script>
<script>
    $(document).ready(function() {
        $('body').on('click', '.modalnofooter-show', function(e) {
            e.preventDefault();
            var me = $(this),
                url = me.attr('href'),
                form = $('.modal-body form'),
                title = me.attr('title');
            $.ajax({
                url: url,
                dataType: 'html',
                success: function(response) {
                    $('#modal-body-nofooter').html(response);
                }
            });

            $('#modal-nofooter').modal('show');
        });
    });
</script>
<script>
    $(function() {
        $('#example1').DataTable({
            responsive: true,
            processing: true,
            serverSide: true,
            order: [
                [2, 'asc']
            ],
            ajax: {
                'url': "{{route('table.pascasidang')}}",
                'type': 'POST',
                'headers': {
                    'X-CSRF-TOKEN': '{{ csrf_token() }}'
                }
            },
            columns: [{
                    data: 'DT_RowIndex',
                    name: 'id_pcs'
                },
                {
                    data: 'skripsi',
                    name: 'skripsi'
                },
                {
                    data: 'tanggal',
                    name: 'tanggal'
                },
                {
                    data: 'action',
                    name: 'action'
                }
            ],
            columnDefs: [{
                "targets": [0, -1],
                "orderable": false,
                "searchable": false
            }]

        });
    });
</script>
@endpush

resources/views/pascasidang/link_download.blade.php
<a href="{{ $url_download }}" target="_blank">{{ $title }}</a>